/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem.UI;

import defencesystem.DefenceStarter;
import defencesystem.SuperDefence;
import defencesystem.observer.enumcls.Strength;
import defencesystem.observer.Observable;
import static defencesystem.observer.Observable.getDefenceList;

/**
 *
 * @author Sonali Peiris
 */
public class MainController extends Observable {
    private static MainController main; 
    private static boolean isSelected =false;
            
    public static MainController getInstance(){
        if(main == null) main = new MainController();
        return main;
    }
    
    private MainController() {
        initComponents();
        displayTextArea.setEditable(false);
        setResizable(false);
    }

    public void setMessage(String msg){
        displayTextArea.setText(displayTextArea.getText()+ msg+ "\n" );          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        collectInforBtn = new javax.swing.JButton();
        areaClearBox = new javax.swing.JCheckBox();
        SendPrivateBox = new javax.swing.JCheckBox();
        mainSendBtn = new javax.swing.JButton();
        mainSlider = new javax.swing.JSlider();
        solidCountLbl = new javax.swing.JLabel();
        FuelAmountLbl = new javax.swing.JLabel();
        ammoAmountLbl = new javax.swing.JLabel();
        PositionLbl = new javax.swing.JLabel();
        selectDefenceComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        sendMsgTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        displayTextArea = new javax.swing.JTextArea();
        SoldierClbl = new javax.swing.JLabel();
        FuelAlbl = new javax.swing.JLabel();
        AmmoAlbl = new javax.swing.JLabel();
        strengthlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        collectInforBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        collectInforBtn.setText("Collect Informations");
        collectInforBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectInforBtnActionPerformed(evt);
            }
        });

        areaClearBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        areaClearBox.setText("Area Clear");
        areaClearBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        areaClearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaClearBoxActionPerformed(evt);
            }
        });

        SendPrivateBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SendPrivateBox.setText("Send Private");
        SendPrivateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendPrivateBoxActionPerformed(evt);
            }
        });

        mainSendBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainSendBtn.setText("Send");
        mainSendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSendBtnActionPerformed(evt);
            }
        });

        mainSlider.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainSlider.setMajorTickSpacing(20);
        mainSlider.setMinorTickSpacing(10);
        mainSlider.setPaintLabels(true);
        mainSlider.setPaintTicks(true);
        mainSlider.setValue(0);
        mainSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateValue(evt);
            }
        });

        solidCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        solidCountLbl.setText("Soldier Count");

        FuelAmountLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FuelAmountLbl.setText("Fuel Amount");

        ammoAmountLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ammoAmountLbl.setText("Ammo Amount");

        PositionLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PositionLbl.setText("Position");

        selectDefenceComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectDefenceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Defence", "Helicopter", "Submarine", "Tank" }));
        selectDefenceComboBox.setName("Select Defence"); // NOI18N

        sendMsgTextArea.setColumns(20);
        sendMsgTextArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendMsgTextArea.setRows(5);
        jScrollPane1.setViewportView(sendMsgTextArea);

        displayTextArea.setColumns(20);
        displayTextArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        displayTextArea.setRows(5);
        displayTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(displayTextArea);

        SoldierClbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SoldierClbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SoldierClbl.setText("00");

        FuelAlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FuelAlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FuelAlbl.setText("00");

        AmmoAlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AmmoAlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AmmoAlbl.setText("00");

        strengthlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        strengthlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strengthlbl.setText("Strength");
        strengthlbl.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(selectDefenceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(collectInforBtn)
                .addGap(18, 18, 18)
                .addComponent(areaClearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(solidCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FuelAmountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ammoAmountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SoldierClbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FuelAlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(AmmoAlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(strengthlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PositionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(SendPrivateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(mainSendBtn))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectDefenceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collectInforBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(areaClearBox)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(solidCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(FuelAmountLbl)
                        .addGap(12, 12, 12)
                        .addComponent(ammoAmountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(SoldierClbl)
                        .addGap(16, 16, 16)
                        .addComponent(FuelAlbl)
                        .addGap(18, 18, 18)
                        .addComponent(AmmoAlbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(strengthlbl))
                    .addComponent(PositionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(SendPrivateBox)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(mainSendBtn)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        selectDefenceComboBox.getAccessibleContext().setAccessibleName("Select Defence");
        selectDefenceComboBox.getAccessibleContext().setAccessibleDescription("Select Defence");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendPrivateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendPrivateBoxActionPerformed
       isSelected=SendPrivateBox.isSelected();
    }//GEN-LAST:event_SendPrivateBoxActionPerformed

    private void mainSendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSendBtnActionPerformed
        String selected=selectDefenceComboBox.getSelectedItem().toString();
        for(SuperDefence sd:getDefenceList()){
        if(isSelected==true){
            if(selected.equalsIgnoreCase(sd.getClass().getSimpleName())){
                sd.setMessage("Private :"+sendMsgTextArea.getText()); 
            }
            }else{
            sd.setMessage("Public : "+sendMsgTextArea.getText()); 
            }
         }
    }//GEN-LAST:event_mainSendBtnActionPerformed

    private void collectInforBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectInforBtnActionPerformed
       String selected=selectDefenceComboBox.getSelectedItem().toString();
       collectInformation(selected);
       SoldierClbl.setText(getSoldierCount()+"");
       AmmoAlbl.setText(getAmmoCount()+"");
    }//GEN-LAST:event_collectInforBtnActionPerformed
    
    private void clearmainTextArea(){
       sendMsgTextArea.setText(null);
       displayTextArea.setText(null);
    }
    
    private void areaClearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaClearBoxActionPerformed
        if (areaClearBox.isSelected()){
            setArealbl("Area Cleared");
            clearmainTextArea();
        }else if(!areaClearBox.isSelected()){
            setArealbl("Area not Cleared");
        }
    }//GEN-LAST:event_areaClearBoxActionPerformed

    private void updateValue(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_updateValue
        Strength s=getStrength();
        strengthlbl.setText(s.name()+" | "+mainSlider.getValue());
        setButtonState(s);
    }//GEN-LAST:event_updateValue
    
    public Strength getStrength(){
        return identifyStrength(mainSlider.getValue());
    }
    
    private Strength identifyStrength(int value){
        if (value<=20){
            return Strength.LOW;
        }else if(value<=40){
            return Strength.MEDIUM;
        }else if(value<=60){
            return Strength.HIGH;
        }else if(value<=80){
            return Strength.STRONG;
        }else{
            return Strength.CLOSED;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main=new MainController();
                main.setVisible(true);
                main.setLocation(200, 0);
                
                DefenceStarter.main(args);
                

                for(int i=0;i<getDefenceList().size();i++){
                    getDefenceList().get(i).setVisible(true);
                    getDefenceList().get(0).setLocation(1000,0);
                    getDefenceList().get(1).setLocation(200,550);
                    getDefenceList().get(2).setLocation(1000,550);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmmoAlbl;
    private javax.swing.JLabel FuelAlbl;
    private javax.swing.JLabel FuelAmountLbl;
    private javax.swing.JLabel PositionLbl;
    private javax.swing.JCheckBox SendPrivateBox;
    private javax.swing.JLabel SoldierClbl;
    private javax.swing.JLabel ammoAmountLbl;
    private javax.swing.JCheckBox areaClearBox;
    private javax.swing.JButton collectInforBtn;
    private javax.swing.JTextArea displayTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton mainSendBtn;
    private javax.swing.JSlider mainSlider;
    private javax.swing.JComboBox<String> selectDefenceComboBox;
    private javax.swing.JTextArea sendMsgTextArea;
    private javax.swing.JLabel solidCountLbl;
    private javax.swing.JLabel strengthlbl;
    // End of variables declaration//GEN-END:variables
}
